layout_spectrum: 0.4183652
typography_spectrum: 0.6782604
color:
  saturation: 0.03022834
  lightness: 0.9622997
  brandStrength: 0.2049174
  rhythmicContrast: 0.8420872
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Hair straightening
